title: Stations
description: Personal Montreal metro assistant
baseurl:
url: https://stationsmontreal.app

timezone: America/Toronto

author:
  name: Laurent Boileau
  twitter: laurentboileau

site_nav_links:
  en:
    - title: Release Notes
      url: "/release-notes"
    - title: Privacy Policy
      url: "/privacy"
    - title: Support
      url: "/support"
  fr:
    - title: Nouveautés
      url: "/fr/nouveautes"
    - title: Confidentialité
      url: "/fr/confidentialite"
    - title: Assistance
      url: "/fr/assistance"

collections:
  release-notes:
    output: true
  nouveautes:
    output: true

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "LICENSE"
  - "README.markdown"

# i18n

title_fr: Stations
description_fr: Assistant personnel du métro de Montréal
url_fr: https://stationsmontreal.app/fr/