# Site settings
title: Stations Montréal
description: Montréal Metro Assistant
url: "https://stationsmontreal.app"

author:
    name: Laurent Boileau
    twitter: laurentboileau

theme:

# Build settings
exclude:
    - Gemfile
    - Gemfile.lock
    - LICENSE
    - README.markdown
plugins:
    - jekyll-seo-tag
    - jekyll-sitemap
sass:
    sass_dir: ./
    style: compressed
